#!/usr/bin/env python

import sys
import csv

# Read a 5-column CSV suitable for contributing to OAR on standard input and
# write a CSV to standard output with a portion of the input rows. The portion
# written to the output depends on the 2 and only two command line arguments
#
# (int)  A mod value
# (bool) If true, rows matching the mod value are written to the output,
#        otherwise rows not matching the mod value are written to the output.
#
# USAGE
#
# segment_csv 50 1 < facility_list.csv > facility_list_small_segment.csv
# segment_csv 50 0 < facility_list.csv > facility_list_large_segment.csv

csv_reader = csv.reader(sys.stdin, delimiter=',')
next(csv_reader)
csv_writer = csv.writer(sys.stdout)
csv_writer.writerow(['country', 'name', 'address', 'lat', 'lng'])

segment = int(sys.argv[1])
include = bool(sys.argv[2])
row_num = 0
for row in csv_reader:
    row_num += 1
    if row_num % segment == 0:
        if include:
            csv_writer.writerow(row)
    else:
        if not include:
            csv_writer.writerow(row)
