#!/usr/bin/env python

import sys
import fileinput
import csv

# Read a CSV downloaded from OAR search results on standard input and
# write a 5-column CSV to standard output suitable for uploading as a
# contributed list.

# USAGE
#
# split_download < facility_list.csv > facility_list_to_upload.csv

csv_reader = csv.reader(fileinput.input(), delimiter=',')
next(csv_reader)
csv_writer = csv.writer(sys.stdout)
csv_writer.writerow(['country', 'name', 'address', 'lat', 'lng'])
for row in csv_reader:
    csv_writer.writerow([row[4], row[1], row[2], row[5], row[6]])
